name: Xeno Media Configuration Split
type: module
description: Creates xeno media configuration split settings
package: Config
core_version_requirement: ^8.8 || ^9
dependencies:
  - config_split:config_split
  - config_ignore:config_ignore
  - stage_file_proxy:stage_file_proxy
